shellEmulator: true

trustPolicy: no-downgrade

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  msgpackr-extract: false
  simple-git-hooks: true
  unrs-resolver: false
  vue-demi: false
